# Generated by Django 3.0.8 on 2021-10-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Chem_e_cross',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('alternate_phone_number', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('current_year', models.IntegerField()),
                ('permanent_address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('pincode', models.IntegerField(null=True)),
            ],
        ),
    ]
