# Generated by Django 3.0.8 on 2021-07-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_ca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='user',
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='alternate_phone_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
