# Generated by Django 3.0.8 on 2021-07-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_ca', '0002_auto_20210727_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
