# Generated by Django 3.2.6 on 2021-08-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_ca', '0003_extendeduser_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
