# Generated by Django 3.0.8 on 2021-12-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_ca', '0006_azeo_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='azeo_id_user',
            name='azeo_id',
            field=models.IntegerField(default=1),
        ),
    ]
