# Generated by Django 3.0.8 on 2021-12-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_ca', '0007_azeo_id_user_azeo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azeo_id_user',
            name='azeo_id',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
